import type { Metadata } from "next"
import "./globals.css"

import { UserProvider } from "@/context/UserContext"

export const metadata: Metadata = {
  title: "Auth App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <UserProvider>
        <body>{children}</body>
      </UserProvider>
    </html>
  )
}
